
spring:
  cache:
    cache-names: table-names,tables
    guava:
      spec: maximumSize=200,expireAfterAccess=600s
  #datasource:
    # TODO: Specify your datasource connection below
    #url: jdbc:[type]://host:port/database
    #username: user
    #password: pwd

shell:
  disabled-commands: >-
    jpa*,jdbc*,jndi*,cron*,dashboard*,date*,egrep*,env*,filter*,java*,jvm*,
    jul*,less*,mail*,man*,shell*,sleep*,sort*,system*,thread*,jmx*,autoconfig*,
    beans*,endpoint*,metrics*

---

# Temporary development profile
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://33.33.33.1:3306/logicpro?zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

---

spring:
  profiles: demo
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:demo-schema.sql
    data:   classpath:demo-data.sql
