
spring:
  cache:
    cache-names: table-names,tables
    guava:
      spec: maximumSize=200,expireAfterAccess=600s
#  datasource:
#    # TODO: Specify your datasource here!
#    url: jdbc:mysql://33.33.33.1:3306/logicpro
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root

---

spring:
  profiles: demo
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:demo-schema.sql
    data:   classpath:demo-data.sql
